### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m1-evaluacion-intermedia-patriciaSR#1]
Really cool job @patriciaSR  !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page

## CSS - other
- [x] Remember that by default, all the headings have a proportional size of their containers so if you want an H1 to have a certain font-size, you'll have to set it up for this tag

Let me know if you have any doubts ;)

Go for it!!

**Comment by patriciaSR** [comment]
Fixed in master! I've also improved and simplified header's margins and paddings.  
Thanks for your tips to improve the exercise :)
